baseURL = "https://naughty-bassi-4c2ba4.netlify.com/"
languageCode = "en-us"
title = "Nachisimo"
theme = "aether"
paginate = 3

[params]
brand = "Nacho"
description = "segtg"
bgimg = "img/background.jpg"